---
- name: Run info play from project
  ansible.builtin.include_tasks: "{{ role_path }}/../../ini_mgs_services.yml"

- name: Templating the replication script
  ansible.builtin.template:
    src: lustre_snapreplication.py.j2
    dest: /lustre/adm/lustre_snapreplication.py
    owner: root
    group: root
    mode: u=rwx,g=rwx,o=r

- name: Templating the replication fixup script
  ansible.builtin.template:
    src: lreplication_fixup.py.j2
    dest: /lustre/adm/lreplication_fixup.py
    owner: root
    group: root
    mode: u=rwx,g=rwx,o=r

- name: Copy service to mgs
  ansible.builtin.copy:
    src: "files/services/lsnapbackup.service"
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: u=rwx,g=rwx,o=r

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: (Re)Start lreplication service
  ansible.builtin.systemd:
    name: lreplication.service
    state: restarted
    enabled: yes