---
- name: Configure multipathd
  vars:
    dm_multipath_sas_jbods:
      primary: "{{ lcfg[inventory_hostname[:-2]]['sas']['primary'] }}"
      secondary: "{{ lcfg[inventory_hostname[:-2]]['sas']['secondary'] }}"
    dm_multipath_defaults_user_friendly_names: "yes"

  ansible.builtin.include_role:
      name: dm_multipath