---
- name: Ensure Python3 and pip are installed
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
    state: present

- name: Copy Python package to target system
  ansible.builtin.copy:
    src: "{{ role_path }}/files/python_package/"
    dest: /tmp/lustre
    mode: "0755"

- name: Install shared.py as a Python package
  ansible.builtin.command:
    cmd: "pip3 install --no-cache-dir /tmp/lustre"
  changed_when: false

- name: Cleanup
  ansible.builtin.file:
    path: /tmp/lustre
    state: absent

- name: Make the directory for adm scripts
  ansible.builtin.file:
    path: /lustre/adm
    state: directory

#- name: Make the directory for python modules
#  ansible.builtin.file:
#    path: /lustre/adm/modules
#    state: directory

#- name: Copy python modules
#  ansible.builtin.copy:
#    src: "{{ item }}"
#    dest: /lustre/adm/modules
#    owner: root
#    group: root
#    mode: u=rwx,g=rwx,o=r
#  with_fileglob:
#    - "plugins/module_utils/*"

- name: Copy script to mgs
  ansible.builtin.copy:
    src: "files/adm/lustre_snapbackup.py"
    dest: /lustre/adm/
    owner: root
    group: root
    mode: u=rwx,g=rwx,o=r

- name: Copy service to mgs
  ansible.builtin.copy:
    src: "files/services/lsnapbackup.service"
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: u=rwx,g=rwx,o=r

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start lsnapbackup service
  ansible.builtin.systemd:
    name: lsnapbackup.service
    state: started
    enabled: yes