---
galaxy_info:
  author: Henrik Ursin
  namespace: kuit
  role_name: dm_multipath
  description: Configuring the dm-multipath driver
  company: KU
  license: BSD-3-Clause

  min_ansible_version: "2.9"
  galaxy_tags: []
dependencies: []

