---
- name: Templating the replication fixup script
  ansible.builtin.template:
    src: lreplication_fixup.py.j2
    dest: /lustre/adm/lreplication_fixup.py
    owner: root
    group: root
    mode: u=rwx,g=rwx,o=r

- name: Run fixup
  ansible.builtin.command: "/lustre/adm/lreplication_fixup.py -f {{ fixup }}"
  register: output_log

- name: Show output.log
  ansible.builtin.debug:
    msg: "{{ output_log }}"

